---
collections:
  - name: ansible.posix
  - name: ansible.windows
  - name: community.general
  - name: community.crypto
  - name: community.vmware
  - name: amazon.aws
  - name: community.aws
  - name: netbox.netbox
  - name: community.zabbix
  - name: ansible.netcommon
  - name: ansible.utils
