[wazuh_linux_k8s_app]
XTR-SRV-CPAPP-K8S ansible_host=172.19.16.29
XTR-SRV-ETCDAPP-K8S ansible_host=172.19.16.28
XTR-SRV-WORKERAPP-K8S ansible_host=172.19.16.27

[wazuh_linux_reenroll_candidates:children]
wazuh_linux_k8s_app

[wazuh_linux:children]
wazuh_linux_k8s_app

[wazuh_linux:vars]
ansible_user=ansible_svc
ansible_ssh_private_key_file=/home/ansible_svc/.ssh/ansible_id
ansible_python_interpreter=auto_silent
ansible_become=true
wazuh_enrollment_group=xtrim-ti-linux-servers

[wazuh_windows]
# Agrega aqui hosts Windows cuando tengan WinRM validado.
# ejemplo-windows ansible_host=192.0.2.10

[wazuh_windows:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
